### ISSUE TITLE
No exception for Elite Kourend Diary and Boots of Stone

### ISSUE THREAD

**Issue by Cyborger1** [mcdogerts/slayer-item#1]
I was taking a look at your code and spotted this little oversight.

Whenever a player gets a task that requires Boots of Stone or one of its variants, you should check Varbit `DIARY_KOUREND_ELITE(7928)` for Elite Kourend Diary completion. If not checked, you'll be erroneously telling these players that they need the boots when they do not.

**Comment by mcdogerts** [comment]
Yeah that was a big oversight on my part. I'll work on this change.

**Comment by mcdogerts** [comment]
Issue resolved in
https://github.com/mcdogerts/slayer-item/commit/996ada7c732d1a11686b635f2c2584444f0170b8
